# Numpy

> 본 포스트는 "파이썬 머신러닝 완벽가이드" 책을 참고하여 정리한 것입니다.

https://numpy.org/

파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지

C/C++과 같은 저수준 언어 기반의 호환 API 제공

다양한 데이터 핸들링 기능 제공

In [65]:
import numpy as np

# ndarray

In [66]:
# ap.array를 사용하여 파이썬 리스트를 ndarray로 변환
array1=np.array([1,2,3])
# 변환 결과 확인
print('array1 type:',type(array1))
# ndarray 차원 출력
print('array1 array 형태:',array1.shape)

array2=np.array([[1,2,3],
                [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [67]:
# ndarray.ndim 이용하여 차원 확인
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


# ndarray 데이터 타입

ndarray 내의 데이터 타입은 같은 데이터 타입만 가능

> 한 개의 ndarray 객체에 int형과 float형이 함께 있을 수 없음


In [68]:
list1=[1,2,3]
print(type(list1))

array1=np.array(list1)
print(type(array1))

# dtype을 이용하여 ndarray내 데이터 타입 확인
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [69]:
# 데이터 타입이 섞여있는 경우, 더 큰 데이터 타입으로 변환

# int+str=str
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

# int+float=float
list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [70]:
# ndarray 내 데이터값 타입 변경 : astype()

# int->float
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

# float->int
array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

# float->int
array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray 생성 : arange, zeros, ones

arange(): 0부터 함수 인자 값-1까지의 값을 순차적으로 ndarray의 데이터값으로 변환

zeros(): 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환

ones(): 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarry를 반환 (dtype default:float64)

In [71]:
# arange
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [72]:
# zeros
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [73]:
# ones
ones_array=np.ones((3,2))
print(ones_array)
print(ones_array.dtype,ones_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray 차원과 크기를 변경하는 reshape()

변경 가능한 차원과 크기일 때만 가능함

In [74]:
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [75]:
# -1 인자를 적용하여 호환되는 사이즈로 자동 변환
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2:\n',array2)
print('shape:',array2.shape)

print('\n')

array3=array1.reshape(5,-1)
print('array3:\n',array3)
print('shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
shape: (2, 5)


array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
shape: (5, 2)


In [76]:
# reshape(-1,1) -> 원본 ndarray가 어떤 형태라도 2차원이고, 반드시 1개의 컬럼을 갖는 ndarray로 변환
array1=np.arange(8)
# 3차원 ndarray 생성
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray -> 2차원 ndarray
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray -> 2차원 ndarray
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6: (8, 1)


# Indexing

* 특정한 데이터만 추출

* Slicing

* Fancy Indexing

* Boolean Indexing

## 단일 값 추출

In [77]:
# 1차원 ndarray에서 단일 값 추출
array1=np.arange(start=1,stop=10)
print('array1:',array1)

value=array1[2]
print('value:',value)
print(type(value))

# -x는 뒤에서 x번째 값
print('맨 뒤의 값:',array1[-1])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9


In [78]:
# 1차원 ndarray에서 단일 인덱스를 이용한 데이터 수정
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [79]:
# 다차원 ndarray에서 단일 값 추출
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

# row:행(axis 0), col:열(axis 1)
print('(row=0, col=0) index 가리키는 값:',array2d[0,0])
print('(row=0, col=1) index 가리키는 값:',array2d[0,1])
print('(row=1, col=0) index 가리키는 값:',array2d[1,0])
print('(row=2, col=2) index 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [80]:
# 1차원 ndarray에서 slicing
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


## Slicing

[start:end]

시작 인덱스를 생략하면 0부터 시작

종료 인덱스를 생략하면 맨 마지막 인덱스로 설정

시작/종료 인덱스를 생략하면 전체 범위를 추출함

In [81]:
# 1차원 ndarray에서 슬라이싱
array1=np.arange(start=1,stop=10)
print("array1:",array1)

# 0부터 2까지
array4=array1[:3]
print(array4)

# 3부터 끝까지
array5=array1[3:]
print(array5)

# 전체 범위
array6=array1[:]
print(array6)

array1: [1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [82]:
# 다차원 ndarray에서 슬라이싱
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

# [행 슬라이싱, 열 슬라이싱]
print('array2d[0:2,0:2] \n',array2d[0:2,0:2])
print('array2d[1:3.0:3] \n',array2d[1:3,0:3])
print('array2d[1:3,:] \n',array2d[1:3,:])
print('array2d[:,:] \n',array2d[:,:])
print('array2d[:2,1:] \n',array2d[:2,1:])
print('array2d[:2,0] \n',array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3.0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


## Fancy Indexing

리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [83]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


## Boolean Indexing

조건 필터링과 검색을 동시에 수행

1) array1d>5와 같이 ndarray의 필터링 조건을 []안에 기재

2) False 값은 무시하고 True 값에 해당하는 인덱스값만 저장

3) 저장된 인덱스 데이터 세트로 ndarray 조회

In [84]:
array1d = np.arange(start=1, stop=10)

# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [85]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [86]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [87]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


## 행렬의 정렬 : sort(), argsort()

* np.sort(): 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환

* ndarray.sort(): 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None


In [96]:
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)

# np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
org_array.sort() 호출 후 원본 행렬: [3 1 9 5]


In [97]:
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)

# ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [98]:
# 내림차순 정렬
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [99]:
# 2차원 이상일 경우 axis 축 값 설정을 통해 정렬 수행
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### np.argsort()를 이용하여 정렬된 행렬의 인덱스 반환

In [102]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


## 선형대수 연산 : 행렬 내적과 전치 행렬

In [103]:
# 행렬 내적(행렬 곱)
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [105]:
# 전치 행렬
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
